---
title: "How i healed The Fearful-Avoidant/Disorganized attachment style within 3 months"
date: 2022-07-31T02:26:36+02:00
draft: true
---
/Hard choices, makes life easier, easy choices makes life harder/

First entry will be special and very personal, because the creation of this blog coincided with drastic changes in my life - the title explains it all - and therefore all other work will be suspended until this problem is resolved.

I didn't know it existed until June this year. Theoretically, there were articles on Wikipedia that he came across, but in the 2008 Polish edition, there was no mention of a disorganized style and I didn't know English at the time, so I lived in ignorance for the rest of my life. 

After a series of countless failures, confusion, mental disorders[fn:1][fn:2][fn:3][fn:4] finally i get rid of.

1. First of all, if you haven't done it yet (I didn't have to, as they didn't have much of an influence on me), forget everything you've seen in pop culture. It have as much to do with the truth as porn with real sex - lies or half-truth at best.
2. Avoid redpill shit, because it's just like [[https://en.wikipedia.org/wiki/Horseshoe_theory][going from extreme to extreme]] and are especially harmful to FA as they fuel your core wound[fn:5]. For example in The Redpill handbook says:
   - Don't trust women. Lying and manipulating is to them what resolve and hard work are for us: our weapons in life.
   - Trust people (even women) to act in their own (perceived) self-interest at all times. You won't be disappointed. By WishIHadMyOldUsernam.
   - How do you trust anyone? Trust yourself, trust your judgement, don't take things personally and don't let others control you. By lonGterMgoalS.
   - Women simply. Are. Not. Loyal.
   - Etc. Confirmation bias is very strong here — they literally promote fearful avoidant and anxious preoccupied attachment. And it's a pseudoscience. Always use primary sources. Don't be fooled. And you guess what? Just because something can happen doesn't mean it will happen. So enjoy it, cherish it.
3. Instead, go to [[https://dacemars.com/best-attachment-books/][scientific books]] ([[https://www.dropbox.com/s/82libykmjs904x4/THE%20BEST%20BOOKS%20TO%20HEAL%20ATTACHMENT%20TRAUMA.zip?dl=0][DOWNLOAD]]) and learn correct attachment style. We are programmed for them by default. Tldr; [[https://en.wikipedia.org/wiki/Emotionally_focused_therapy][Emotional Focused Therapy (EFT)]].
4. If you feel stuck, don't worry. This is not speedrun, just a process. These books are so structured that you can be cured without consulting a psychotherapist. I was very determined to do this for two reasons: first is that in Poland [[https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Mental_health_and_related_issues_statistics][we have worst possible care of mental health (9.2 per 100 000 inhabitants) over the EU]]) second, because the core wound is trust issue, there may be a problem with trusting a psychotherapist.

Hovewer, i also was very lucky, because i meet person with a secure attachment style during the course, so i may be biased a little bit. Of course i has sabatted like a typical FA but it teaches so much.

Warning: Don't let my dry description deceive you, be prepared that the whole process can be terribly unpleasure.

* Further reading
- [[https://www.youtube.com/channel/UC1HEAeAswWMZUKum2C2YFSA][Paulien Timmer - Healing the fearful avoidant]] — IMO Best resource ever made for recognizing patterns (I wish it had existed in my youth!)
- [[https://joyninja.com/fearful-avoidant-attachment-how-to-heal/][Redeeming qualities]]
- [[https://www.tandfonline.com/doi/pdf/10.1080/10508619.2013.795821][Comparing Attachment Theory and Buddhist Psychology]] (Subscription required.)

* Acknowledgements:
- wariatnakaftan — for forcing changes that I would never have dared otherwise. It just wouldn't be possible.
- silent_girl — for support and wisdom.

/Never underestimate the importance of people who are kind to you — Bear grylls, A Survival Guide for Life (25 chapter)/
* Footnotes
[fn:1] [[https://www.sciencedirect.com/science/article/pii/S2468749922000096][The role of fearful attachment in depersonalization disorder]]
[fn:2] [[https://bpspsychub.onlinelibrary.wiley.com/doi/abs/10.1111/j.2044-8341.2011.02028.x][Adult attachment insecurities are associated with obsessive compulsive disorder]]
[fn:3] [[https://journals.lww.com/jonmd/Fulltext/2001/05000/Alexithymia_and_Attachment_Representation_in.7.aspx][Insecure Attachment and Alexithymia in Young Men with Mood Symptoms]]
[fn:4] [[https://www.sciencedirect.com/science/article/pii/S002239562200019X][Social anxiety disorder with comorbid major depression – why fearful attachment style is relevant]]
[fn:5] https://www.thehealingfairee.com/s/How-to-Heal-Attachment-Styles-Workbook.pdf
